version: '3.5'
services:
    mysql:
      image: mysql:5.7
      hostname: quickstart-mysql
      container_name: quickstart-mysql
      ports:
       - 3306:3306
      environment:
        - MYSQL_DATABASE=connect_test
        - MYSQL_ROOT_PASSWORD=confluent
        - MYSQL_USER=confluent
        - MYSQL_PASSWORD=confluent
      volumes:
        - ${PWD}/dump_2019_01_15.sql:/dbscript/dump_2019_01_15.sql:ro
      networks:
       - kafka_network
    elasticsearch:
      image: elastic/elasticsearch:6.6.0
      hostname: elasticsearch
      container_name: elasticsearch
      ports:
        - 9200:9200
        - 9300:9300
      environment:
        - "discovery.type=single-node"
      networks:
       - kafka_network
networks:
  kafka_network:
    external: true
    name: kafka_network
